# Generated by Django 3.1.7 on 2021-03-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('num_pages', models.IntegerField(max_length=1000)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
