# Generated by Django 3.1.7 on 2021-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210320_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
