# Generated by Django 3.1.7 on 2021-03-20 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='due',
            field=models.DateField(default=datetime.date(2021, 3, 22)),
        ),
        migrations.AddField(
            model_name='journal',
            name='due',
            field=models.DateField(default=datetime.date(2021, 3, 22)),
        ),
    ]
