# Generated by Django 3.1.7 on 2021-03-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210320_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='due',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='due',
        ),
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('Bl', 'Bullet'), ('Fd', 'Food'), ('Tl', 'Travel'), ('Sp', 'Sport')], default='Bl', max_length=20),
        ),
    ]
