# Generated by Django 3.1.7 on 2021-03-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
    ]
